version: "3.3"
services:
  backend:
    image: registry.gitlab.com/gsdiamondscore/backend:{IMAGE_TAG}
    sysctls:
      - net.core.somaxconn=20000    
    volumes:
      - './.env:/var/www/html/.env'
      - './nginx.conf:/etc/nginx/sites-enabled/default.conf'
      - './docker-vars.ini:/usr/local/etc/php/conf.d/docker-vars.ini'
    ports:
          - "801:80"        
    restart: 
       unless-stopped
    networks:
      - diamond

  worker:
    image: registry.gitlab.com/gsdiamondscore/backend:{IMAGE_TAG}
    sysctls:
      - net.core.somaxconn=20000    
    volumes:
      - './.env:/var/www/html/.env'
      - './worker_supervisord.conf:/etc/supervisord.conf'
      - './docker-vars.ini:/usr/local/etc/php/conf.d/docker-vars.ini'
    restart: 
       unless-stopped
    networks:
      - diamond

networks:
  diamond:
    driver: bridge

